**CraxLab.net | CxL | Department of Civil Engineering | Sakarya University**

---
Note: Examples were taken from Dr. Hakan Ozturk's Structural Dynamics course notes

**Example 1:**

<img src="./figures_files/fku.png" align="left"/>

In [1]:
import numpy as np

k1 = 1000
k2 = 500

F1 = 0
F2 = 200


K = np.array([[k1+k2, -k2] ,\
              [-k2,    k2, ]   ])
print(K)

F = np.array([[F1, F2]]).T
print(F)

u = np.linalg.solve(K, F)
print(u)

[[1500 -500]
 [-500  500]]
[[  0]
 [200]]
[[0.2]
 [0.6]]


---
**Example 2:**

<img src="./figures_files/fku2.png" align="left"/>

In [2]:
k1 = 1000
k2 = 800
k3 = 600

F1 = 200
F2 = 400
F3 = 600

K = np.array([[k1+k2, -k2,   0] ,\
              [-k2,  k2+k3, -k3] ,\
              [ 0,   -k3,    k3]  ])
print(K)

F = np.array([[F1, F2, F3]]).transpose()
print(F)

u = np.linalg.solve(K, F)
print(u)

[[1800 -800    0]
 [-800 1400 -600]
 [   0 -600  600]]
[[200]
 [400]
 [600]]
[[1.2 ]
 [2.45]
 [3.45]]
